import type { Metadata } from 'next'
import Providers from '@/components/Providers'
import TopNav from '@/components/navbar/TopNav'

import '@/styles/global.css'

export const metadata: Metadata = {
	title: 'Next chat',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<TopNav />
					<main className='container max-auto p-10'>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
