import type { Metadata } from 'next'
import Providers from '@/components/Providers'
import TopNav from '@/components/navbar/TopNav'

import '@/styles/global.css'

export const metadata: Metadata = {
	title: 'Next chat',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
	params: { locale: string }
}

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<RootLayoutProps>) {
	console.log(locale)
	return (
		<html lang={locale}>
			<body>
				<Providers>
					<TopNav />
					<main className='container max-auto p-10'>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
