import '@/styles/global.css'

import type { Metadata } from 'next'
import { ReactNode } from 'react'

import TopNav from '@/components/navbar/TopNav'
import Providers from '@/components/Providers'

export const metadata: Metadata = {
	title: 'Next chat',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: ReactNode
	params: { locale: string }
}

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<RootLayoutProps>) {
	return (
		<html lang={locale}>
			<body>
				<Providers>
					<TopNav />
					<main className='container mx-auto'>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
