import '@/styles/global.css'

import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { ReactNode } from 'react'

import { auth } from '@/auth'
import TopNav from '@/components/navbar/TopNav'
import ProvidersClient from '@/components/Providers'

// TODO: Change with i18n-intl before deploy
export const metadata: Metadata = {
	title: 'Next chat',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: ReactNode
	params: { locale: string }
}

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<RootLayoutProps>) {
	const messages = await getMessages()
	const session = await auth()
	const userId = session?.user?.id || null
	const profileComplete = session?.user.profileComplete
	const AsyncTopNav: JSX.Element = await TopNav()

	return (
		<html lang={locale}>
			<body>
				<NextIntlClientProvider messages={messages}>
					<ProvidersClient userId={userId} profileComplete={profileComplete}>
						{/* <TopNav /> */}
						{AsyncTopNav}
						<main className='container mx-auto px-3'>{children}</main>
					</ProvidersClient>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
